name: Bump Version

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

      - name: Get latest tag
        id: get_tag
        run: echo "LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

      - name: Update versionCode and versionString
        run: |
          current_code=$(grep 'versionCodeOverride = ' android/app/build.gradle | grep -oE '[0-9]+')
          echo current_code
          new_code=$((current_code+1))
          echo ${{ steps.get_tag.outputs.LATEST_TAG }}

          bumpVersion=${{ steps.get_tag.outputs.LATEST_TAG }}

          sed -i "s|MARKETING_VERSION = .*;|MARKETING_VERSION = $bumpVersion;|g" "./ios/MyApp.xcodeproj/project.pbxproj"
          sed -i "s|CURRENT_PROJECT_VERSION = .*;|CURRENT_PROJECT_VERSION = $new_code;|g" "./ios/MyApp.xcodeproj/project.pbxproj"
          sed -i "s|versionCode .*|versionCode $new_code|g" "./android/app/build.gradle"
          sed -i "s|versionCodeOverride = .*|versionCodeOverride = $new_code|g" "./android/app/build.gradle"   

          sed -i "s|-firebase|-production|g" "./ios/MyApp/Supporting/Expo.plist" 
          sed -i "s|-firebase|-production|g" "./android/app/src/main/AndroidManifest.xml" 
          sed -i "s|<string>v.*<\/string>|<string>v$bumpVersion-production</string>|g" "./ios/MyApp/Supporting/Expo.plist"
          sed -i "s|EXPO_RELEASE_CHANNEL\" android:value=\".*\"|EXPO_RELEASE_CHANNEL\" android:value=\"v$bumpVersion-production\"|g" "./android/app/src/main/AndroidManifest.xml"

          sed -i "s|versionName \".*\"|versionName \"$bumpVersion\"|g" "./android/app/build.gradle"
          sed -i "s|appVersion: [^ ]*|appVersion: '$bumpVersion',|" "./App/Config/envs/default.ts"
          sed -i "s|expoVersion: [^ ]*|expoVersion: '$bumpVersion',|" "./App/Config/envs/default.ts"
          sed -i "s|\"version\": [^ ]*|\"version\": \"$bumpVersion\",|" "./package.json"
        env:
          NEW_VERSION: ${{ steps.latest_tag.outputs.version }}
      - uses: EndBug/add-and-commit@v9
        with:
          message: Bump Version
          committer_name: GitHub Actions
          committer_email: actions@github.com
          token: ${{ secrets.GITHUB_TOKEN }}
